### PR TITLE
Migrate to pydata-sphinx-theme

### LINKED ISSUE #741: readthedocs version switcher (=flyout) is missing from docs
readthedocs version switcher is missing from docs

for context see https://github.com/executablebooks/sphinx-book-theme/issues/596

also here the implementation of sphinx-book-theme in their own docs in `conf.py` https://github.com/executablebooks/sphinx-book-theme/blob/c47d8e46fbce78492abd8a5adfe41083bb7ba121/docs/conf.py#L213-L224

@OrtnerMichael  have a look there :)

### LINKED ISSUE #781: Search on readthedocs never returns anything
### Magpylib version

5.x (Latest)

### What happened?

Hello, 

after reading in the [docs](https://magpylib.readthedocs.io/en/latest/) a bit, I tried finding something specific with the search bar. 

No matter what I enter there, e.g. magnet, wire, magpylib or even "and", nothing is returned. 

I am running in dark mode, i disabled Dark Reader and ublock for the site, reloaded and tried again, but no success. The search result area remains empty. 

### Code example

_No response_

### Additional context

Firefox 126.0 (64-bit) on Fedora 40, Gnome 46.

### PR DESCRIPTION
**Pull request by Alexboiboi**
**Merge after #776**

### Related issues
- Fixes #741
- Fixes #781

The pydata-sphinx-theme is quite widely used in the scientific python community and has the version switcher integrated. We will loose the live code feature though. 

Note that the version switcher does not work locally or on the PR rtd link. We will have to merge first ( see https://github.com/pydata/pydata-sphinx-theme/issues/647)

### CODE REVIEW

**Comment by OrtnerMichael** [comment]
hi @Alexboiboi 

Its nice.
It would require restructuring the webpage a little bit - nothing that cannot be done quickly.

But I also see no major advantage - except that the version switcher is there.

What do you think ? What would be major reasons to switch ?

br michael

**Comment by Alexboiboi** [comment]
Hi @OrtnerMichael, 

I just bumped sphinx version from 7.2 to 7.3.  This solved the search issue raised in #781 and as a side effect the flyout is now also back ^^

**Comment by Alexboiboi** [comment]
@OrtnerMichael You will need to tell me when this PR is ready for review btw ;)

**Review by OrtnerMichael — APPROVED** [review]
i thinks its good to go now ... will need a review on rtd especilly for the version switcher ....

**Pull request merged**
