### PR TITLE
Pyvista plotting backend

### PR DESCRIPTION
**Pull request by Alexboiboi**
# Related Issues
#537, #539 

This PR implements a new [pyvista](https://docs.pyvista.org/) using the new plotting logic from #539.

# Remarks
Pyvista itself supports different backends, more specifically `jupyter_backends` of which not everyone supports the same features.
- No support for marker or line styling
- No custom color map for ipygany backend
- Color map with ipythreejs backend does not render properly

# Feature parity checks| Feature type | Possible?

| Feature type | Compatibility|
|  ---  |  ---  |
| triangular mesh 3d | ✔️ | 
| line/scatter 3d | ✔️ | 
| line color | ✔️ | 
| line width | ✔️ | 
| line style | ❌ | 
| marker | ✔️ | 
| marker color | ✔️ | 
| marker size | ✔️ | 
| marker symbol | ❌ | 
| marker numbering | ❌ | 
| zoom level  | ❌ | 
| color scale | ✔️ | 
| custom color scale | ✔️ | 
| custom color scale for  individual objects | ✔️ | 
| animation | ❌ | 
| animation time | ❌ | 
| animation fps | ❌ | 
| animation slider | ❌ | 

# Tasks
- [x] changelog
- [x] tests
- [x] docstrings
- [x] docs

### CODE REVIEW

**Comment by OrtnerMichael** [comment]
One bug: The feature `style.path.line.style` is now deactivated for all backends.

using the command `loop.style.path.line.style = ':'`

with main branch

image

with pyvista branch:

image

**Comment by OrtnerMichael** [comment]
Pyvista has a differently set standard orientation than matplotlib and plotly


image

**Comment by OrtnerMichael** [comment]
@Alexboiboi 
I improved the backend-canvas examples, but I did not manage to generate the pyvista output (at the end of the page) with sphinx ... any idea ?

**Comment by Alexboiboi** [comment]
> 1. The feature `style_path_line_style` defaults to `'-'` when using matplotlib backend (works in plotly)
> 2. `style_marker_symbol` input not accepted in Matplotlib backend (works in plotly)
fixed by [6cf4094](https://github.com/magpylib/magpylib/pull/548/commits/6cf4094c47d30c89503daf0ac36eacea2d4bc90e)

> Things that work with pyvista, but you claim above that they dont:
> 
> 1. The path style property `...line.width`
> 2. Markers also appear in pyvista.
> 3. `style_marker_size` also works in pyvista
> 4. `style_marker_color` also works in pyvista
corrected in comment above

> By coloring and color scales you mean the magnetization color scales and all body color properties ?
Yes

**Review by OrtnerMichael — APPROVED** [review]
looks great now !

**Pull request merged**
