### PR TITLE
Magnetization mode + Triangle orientation visualization feature 

### PR DESCRIPTION
**Pull request by Alexboiboi**
# Related Issues
- #574

# Notes
This PR addresses  the issue of displaying magnetization arrows for any backend (see https://github.com/magpylib/magpylib/pull/574#discussion_r1083727411)

Also included in the PR is the new `orientation` style for triangular facets

## Magnetization mode
Until now, if the backend was capable of displaying color gradients, the magnetization direction was only shown via colors. On the other hand, if the backend is not capable of it, it displays arrows. With the now `magnetization.mode` (`'auto', 'arrow', 'color', 'arrow+color'`). Magnetization can be displayed via arrows, color or both. By default `mode='auto'` means that the chosen backend determines which mode is applied by its capability. If the backend can display both and `auto` is chosen, the priority is given to `color`. 

```python
import magpylib as magpy
import pyvista as pv
pv.set_jupyter_backend('panel')
vertices = [
    ([0, 1, -1], [-1, 1, 0], [1, 1, 0]),
    ([0, 1, 1], [1, 1, 0], [-1, 1, 0]),
]

cuboc = magpy.Collection(style_label="cuboc")
for ind, vert in enumerate(vertices):
    cuboc.add(
        magpy.misc.Triangle(
            magnetization=(100, 200, 300),
            vertices=vert,
        )
    )


for backend in magpy.SUPPORTED_PLOTTING_BACKENDS:
    for mode in ("auto", "arrow", "color", "arrow+color"):
        print(backend, f"{mode=}")
        magpy.show(
            *cuboc,
            backend=backend,
            style_magnetization_mode=mode,
        )
```
<p float="left">
  
   
  
</p>

## Triangle orientation display feature

This features add a visualization of triangular facets orientations with some additional settings

```python
"""
show: bool, default=True
    Show/hide orientation symbol.

size: float, default=1,
    Size of the orientation symbol

color: dict or MagnetizationColor object, default=None
    Color properties of the triangle orientation.

pivot: str, default=None
    The part of the orientation symbol that is anchored to the X, Y grid.
    The orientation symbol rotates about this point. Can be one of `['tail', 'middle', 'tip']`.

symbol: {"cone", "arrow3d"}:
    Orientation symbol for the triangular facets.
"""
```

- example:

```python
import magpylib as magpy

magpy.defaults.display.style.triangle.orientation.size = 2

vertices = [
    ([0, 1, -1], [-1, 1, 0], [1, 1, 0]),
    ([0, 1, 1], [1, 1, 0], [-1, 1, 0]),
    ([0, 1, 1], [-1, 0, 1], [0, -1, 1]),
    ([0, 1, 1], [0, -1, 1], [1, 0, 1]),
    ([0, 1, -1], [1, 0, -1], [0, -1, -1]),
    ([0, 1, -1], [0, -1, -1], [-1, 0, -1]),
    ([0, -1, 1], [-1, -1, 0], [1, -1, 0]),
    ([0, -1, -1], [1, -1, 0], [-1, -1, 0]),
    ([-1, 1, 0], [-1, 0, -1], [-1, 0, 1]),
    ([-1, -1, 0], [-1, 0, 1], [-1, 0, -1]),
    ([1, 1, 0], [1, 0, 1], [1, 0, -1]),
    ([1, -1, 0], [1, 0, -1], [1, 0, 1]),
    ([0, 1, 1], [-1, 1, 0], [-1, 0, 1]),
    ([0, 1, 1], [1, 0, 1], [1, 1, 0]),
    ([0, 1, -1], [-1, 0, -1], [-1, 1, 0]),
    ([0, 1, -1], [1, 1, 0], [1, 0, -1]),
    ([0, -1, -1], [-1, -1, 0], [-1, 0, -1]),
    ([0, -1, -1], [1, 0, -1], [1, -1, 0]),
    ([0, -1, 1], [-1, 0, 1], [-1, -1, 0]),
    ([0, -1, 1], [1, -1, 0], [1, 0, 1]),
]

cuboc = magpy.Collection(style_label="Cuboctahedron")
for ind, vert in enumerate(vertices):
    cuboc.add(
        magpy.misc.Triangle(
            magnetization=(100, 200, 300),
            vertices=vert,
            style_label=f"Triangle_{ind+1:02d}",
        )  # .rotate_from_angax(45, 'x')
    )

# flip a triangle
tri = cuboc[3]
tri.vertices = tri.vertices[[0,2,1]]
tri.style.orientation = dict(pivot="tail", symbol="arrow3d", color="black", size=4)


magpy.show(
    *cuboc,
    backend="plotly",
    layout_height=800
)
```

image

# Tasks

- [x] No matter the magnetization mode, magpylib will always show magnetization if `magnetization.show=True` ( e.g. `backend="matplotlib", `magnetization.mode="color" -> arrows will still be shown`
- [x] `orientation.show=True`  by default
- [x] `magnetization` parameters of `Triangle`are not shared with magnets
  - [x] `magnetization.color.mode='tricycle'`
- [x] Review `Triangle` examples @OrtnerMichael   
- [x] orientation symbol size proportional to square root of triangle area (factor ok? )

### CODE REVIEW

**Comment by OrtnerMichael** [comment]
Hi @Alexboiboi 

Here my review (not focusing on the code yet):

# Features

**style_magnetization_mode**
  - works
  - default should not be 'tricycle' but 'tricolor'

**style_orientation_color**
  - works
  - default should be '.3' (instead of current body color because the latter is not visible very well in many cases)

image

**style_orientation_size**
  - works

**style_orientation_pivot**
  - works
  - by default maker should be floating in front of triangle with a tiny gap (avoid overlap on backside)
  - I think this is not very useful feature -> is it a bug ? (I dont think we need so many graphic choices)

image

**style_orientation_symbol**
  - works
  - default should be 'arrow3d' (cone is nice, but arrow3d looks much better I think)
  - also not very useful to switch between different representations -> is it a bug ?

# Bug

Rotation anchor is not used correctly to determine arrow positions

``` python
cuboc.rotate_from_angax(45, (1,2,3), (5,0,0))
```

creates this

image

**Comment by Alexboiboi** [comment]
> * Default: orientation.show = True
> * Default: magnetization.color.mode = 'tricolor' (not 'tricycle')

ok can do

> * Why are magnetization parameters not shared with magnets ? If its possible we should share.
> * orientation.size = 1, the way it is implemented right now, looks good to me

Since the object style defaults are grouped into magnets, currents, dipole, sensor we cannot on the same time have the orientation parameter only for triangles, while having it in the magnets group.  And we need it in this group if we want to share the mag parameters.
It is maybe possible to make it work though but this would need a complete rethinking of the whole style structure. Additionally, since  Triangles are fundamentally very different that actual magnets, I like the idea that they have their own default parameters. Anyway this only affect setting defaults. For individual styles, it does not change anything, and in the show function it applies anyway also in both cases.

> **style_orientation_pivot**
> * by default maker should be floating in front of triangle with a tiny gap (avoid overlap on backside)
> * I think this is not very useful feature -> is it a bug ? (I don't think we need so many graphic choices)

the tiny offset is intentional to make it visible from the other side


> * default should be 'arrow3d' (cone is nice, but arrow3d looks much better I think)
> * also not very useful to switch between different representations -> is it a bug ?

to be able to switch between representation is a feature, in case you have a dipole in your visualization, you don't want get confused by the orientation symbol. We can use the arrow3d by default and still keep the cone option as backup in case it the situation aforementioned happened.

> # Bug
> Rotation anchor is not used correctly to determine arrow positions

should have been fixed in last push, please check

**Comment by OrtnerMichael** [comment]
@Alexboiboi checklist 

- [ ] Default: magnetization.color.mode = 'tricolor' (not 'tricycle')
- [ ] Share magnetization parameters with magnet group
- [x] Default: orientation.show = True
- [ ] Default: orientation.color = '.3' (instead of body color)
- [x] orientation.size = 1
- [ ] orientation.pivot discussion
   - [ ] float or intersect
   - [ ] keep as graphic style
- [ ] orientation.symbol discussion
   - [ ] default value arrow or cone
   - [x] keep as graphic style
- [x] fix rotation anchor bug

**Comment by Alexboiboi** [comment]
@OrtnerMichael 

All changes should now be implemented, 

please still check again and especiallly
- size factor (proportional to sqrt of triangle area * factor)
- doc examples

**Comment by OrtnerMichael** [comment]
@Alexboiboi 

1. `orientation.offset` lässt jetzt nur zahlen zwischen 0 und 1 zu. war das so gedacht ? Ich dachte wir hatten uns auf beliebige verschiebeung [-inf, inf] geeinigt.
2. BUG: `style_orientation_show=False` funktioniert nicht. Kann orientation nicht mehr abschalten.
3. wasndas ? `+++ {"tags": []}`

Sonst passt alles. Hab die examples reviewed und angepasst.

**Comment by Alexboiboi** [comment]
> 1. `orientation.offset` only allows for floats between between [0, 1]
I thought it should not really be allowed to "disconnect" completely the arrow from the triangle. Otherwise it could look very confusion in some situations, we can still open the range if needed in a later release. Ok for you or you still want to change it ?

> 2. BUG: `style_orientation_show=False` funktioniert nicht. Kann orientation nicht mehr abschalten.
forgot to implement it ^^ -> fixed in last push

> 3. wasndas ? `+++ {"tags": []}`

it is a markdown syntax introduced by jupytext, to allow tags for jupyter cells. You can just ignore it

**Comment by OrtnerMichael** [comment]
@Alexboiboi 

please increase the thickness of thick triangle a little bit - the current setting leads to graphic problems in plotly (not in pyvista) like this one: 

image

While you are at it, may also do the `orientation.offset` ? letting it disconnect can be quite helpful, and its just a minor thing no ?

**Comment by Alexboiboi** [comment]
> please increase the thickness of thick triangle a little bit - the current setting leads to graphic problems in plotly (not in pyvista) like this one:

please provide the code. I am not sure it is going to change anything but I can try

> While you are at it, may also do the `orientation.offset` ? letting it disconnect can be quite helpful, and its just a minor thing no ?

ok

**Review by OrtnerMichael — APPROVED** [review]
Looks complete now

**Pull request merged**
