### PR TITLE
Add `show` and `fig` underscore magic to `magpylib.show(...)` and `style.legend.show` property

### LINKED ISSUE #650: showlegend in plotly
I think we have talked about this before:

The plotly legend is sometimes very annoying because it takes up a lot of space. Especially when using `show_context` and multiple columns.

The problemis easily fixed by disabling it - but it requires a figure return ..

```python
# some magpylib code

fig = magpy.show(........, return_fig=True, backend='plotly')
fig.update_layout(showlegend=False)
fig.show()
```

and is very annoying. And how does this work with `show_context` ?

Can we not simply have `showlegend` as kwarg to enable//disbale the legend ?

### LINKED ISSUE #654: Custom Source Bug #1
When the default trace of a `CustomSource` is removed, it does not appear in the legend

```python
import numpy as np
import magpylib as magpy

c1 = magpy.misc.CustomSource(
    style_label="c1",
    style_model3d_showdefault=False
)
xs = 1.1*np.array([-1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, 1,  1, -1])
ys = 1.1*np.array([-1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1])
zs = 1.1*np.array([-1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1])
trace = dict(
    backend='matplotlib',
    constructor='plot',
    args=(xs, ys, zs),
    kwargs={'ls':'--', 'marker':'', 'lw':1, 'color':'k'},
)
c1.style.model3d.add_trace(trace)

c2 = magpy.misc.CustomSource(
    style_label="c2",
)

magpy.show(c1, c2, zoom=10)
```

image

### LINKED ISSUE #655: CustomSource Bug #2
When the default trace of a custom source is removed, and only the custom source is displayed, the zoom option does not work !!!

```python
import numpy as np
import magpylib as magpy

c1 = magpy.misc.CustomSource(
    style_label="c1",
    style_model3d_showdefault=False
)
xs = 1.1*np.array([-1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, 1,  1, -1])
ys = 1.1*np.array([-1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1])
zs = 1.1*np.array([-1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1])
trace = dict(
    backend='matplotlib',
    constructor='plot',
    args=(xs, ys, zs),
    kwargs={'ls':'--', 'marker':'', 'lw':1, 'color':'k'},
)
c1.style.model3d.add_trace(trace)

magpy.show(c1, zoom=1000)
```

image

### PR DESCRIPTION
**Pull request by Alexboiboi**
## Related Issues
- Fixes #650 
- Fixes #654 
- Fixes #655 

### `fig` and `show` kwargs magic
In the same vein as the style magic:
- kwargs with `fig` prefix are forwarded to the figure constructor (`Figure` for mpl and plotly, `Plotter` for pyvista)
- kwargs with `show` prefix are forwarded to the `show` call (for all backends)
- if `fig` or `show` are prefixed with a backend name, the kwargs will only be forwarded to the specific backend.

Here an example below with increasing order of precedence:
```python
import magpylib as magpy

c = magpy.magnet.Cuboid((0, 0, 1000), (1, 1, 1))
c.show(
    fig=dict(layout_title_text="fig"),
    fig_layout_title_text="fig_layout",
    plotly_fig=dict(layout_title_text="plotly_fig"),
    plotly_fig_layout_title_text="plotly_fig_layout",
    backend="plotly",
)
```

### `legend` style

For the legend I introduced it at the object level as `style.legend.show`. The advantage is, that you one can turn off specific traces at will.

```python
magpy.show(..., style_legend_show=False) # hides all legends
```

### CODE REVIEW

**Comment by Alexboiboi** [comment]
One example to test the legends

```python
import magpylib as magpy
import numpy as np

objs = []
f=0.5
N = 3
xs = f * np.array([-1, -1, 1, 1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, -1])
ys = f * np.array([-1, 1, 1, -1, -1, -1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1])
zs = f * np.array([-1, -1, -1, -1, -1, 1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1])
trace_mpl = dict(
    backend="matplotlib",
    constructor="plot",
    args=(xs, ys, zs),
    kwargs={"marker": "", "lw": 1},
)
trace_plotly = dict(
    backend="plotly",
    constructor="scatter3d",
    kwargs={"x": xs, "y": ys, "z": zs, "mode": "lines"},
)
trace_generic = dict(
    backend="generic",
    constructor="scatter3d",
    kwargs={"x": xs, "y": ys, "z": zs, "mode": "lines"},
)
objs.append(magpy.misc.CustomSource(style_label="Matplotlib extra trace"))
objs[-1].style.model3d.add_trace(trace_mpl)

objs.append(magpy.magnet.Cuboid((0,0,1000), [1]*3, style_label="Plotly extra trace"))
objs[-1].style.model3d.add_trace(trace_plotly)

objs.append(magpy.magnet.Cuboid((0,0,1000), [1]*3, style_label="Generic extra trace"))
objs[-1].style.model3d.add_trace(trace_generic)

for i, obj in enumerate(objs):
    obj.rotate_from_angax([10 * i for i in range(N)], "y", start=0, anchor=(0, 0, 10))
    obj.move((0,2*i,0))
for backend in ("matplotlib", "plotly"):
    magpy.show(
        *objs,
        backend=backend,
        style_path_frames=2,
        #style_legend_show=False,
        #style_model3d_showdefault=False,
    )
```

**Comment by Alexboiboi** [comment]
@OrtnerMichael ready for review

**Comment by OrtnerMichael** [comment]
hi @Alexboiboi 

---------------------

`style_legend_show=True/False` works nicely !!! HUGE fan of this !!!

Question: do we have a `format` option for legend display style ? like we have it in `describe` ?

----------------------

`show`  commands I don't understand where kwargs are sent. there is also no example.

---------------------

`fig` commands:

1. Works beautifully with **Plotly**

2. Not very helpful with **Matplotlib** because all the styling happens at `Axes` level. At Figure level there is very little to configure.
```
magpy.show(s1,s2,sens,
    backend='matplotlib',
    fig_facecolor="pink",
)
```
image

We could offer `fig` sensing to `Figure` and `ax` sending to `Axes`

3. Also not helpful with **Pyvista** because the `Plotter` constructor does not accept kwargs - all styles are set via methods/properties. Maybe we can add the styles via the methods ?

```
magpy.show(s1,s2,sens,
    backend='pyvista',
    fig_background_color="pink",
)
```
image

should be done like this
```
pl = pv.Plotter()
# add Magpylib stuff
pl.background_color = "pink"
pl.show()
```

-------------------------

We really need a set of excellent examples and use-cases. I already outlined them in #650. Lets bring them here in the next comment.

**Comment by OrtnerMichael** [comment]
**List of use-cases**

- change background color
- change figure title
- remove axes
- set camera angle

**Review by OrtnerMichael — APPROVED** [review]
passt

**Pull request merged**
