### PR TITLE
add force package

### PR DESCRIPTION
**Pull request by OrtnerMichael**
Check if tests are working ... no idea why force branch is failing

### CODE REVIEW

**Comment by Alexboiboi** [comment]
can we close this?

**Comment by OrtnerMichael** [comment]
this was just a test

**Comment by Alexboiboi** [comment]
There is actually no need to create a PR to test the CI steps. The unit tests are also triggered on push events. If don't want to pollute the current branch commit history with this kind of manual checks, just create a new branch and check the actions tab on github where you can see the results of CI after push.

**Comment by OrtnerMichael** [comment]
ok boss

**Pull request closed without merging**
