### PR TITLE
`getBH` DataFrame output

### PR DESCRIPTION
**Pull request by Alexboiboi**
This PR implements a [pandas DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html) as alternative output object for the `getB` and `getH`. Dataframes are indeed a convenient way to store multidimensional data in a 2D table, and can easily be used to plot field data.

Current work @https://github.com/magpylib/magpylib/tree/getBH-dataframe

# Tasks
- [x] implemented main functionality
- [x] Agree on output-type argument : `output` (`ndarray` by default, optionally `dataframe`) @OrtnerMichael 
- [x] Agree on DataFrame columns : `['source', 'path',  'sensor', 'pixel', 'Bx', 'By', 'Bz']` (or `'Hx', 'Hy', 'Hz'`) @OrtnerMichael 
- [x] Agree on using labels or repr if no label for source/sensor object entries @OrtnerMichael 
- [x] pandas stays an optional dependency
- [x] tests
- [x] docs
- [x] changelog
- [x] docstrings

# Example
```python
import numpy as np
import magpylib as magpy

max_path_len =20
num_of_pix = 2

sources = [
    magpy.magnet.Cuboid((0, 0, 1000), (1, 1, 1)).move(
        np.linspace((-4, 0, 0), (4, 0, 0), max_path_len), start=0
    ),
    magpy.magnet.Cylinder((0, 1000, 0), (1, 1), style_label="Cylinder1").move(
        np.linspace((0, -4, 0), (0, 4, 0), max_path_len), start=0
    ),
]
pixel = np.linspace((0, 0, 0), (0, 3, 0), num_of_pix)
sens1 = magpy.Sensor(position=(0, 0, 1), pixel=pixel, style_label=f"sens1")
sens2 = sens1.copy(position=(0, 0, 3), style_label=f"sens2")
sens_col = magpy.Collection(sens1, sens2)
sensors = sens_col.sensors_all
B = magpy.getB(sources, sens_col, sumup=False, output='dataframe')
B
```

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>source</th>      <th>path</th>      <th>sensor</th>      <th>pixel</th>      <th>Bx</th>      <th>By</th>      <th>Bz</th>    </tr>  </thead>  <tbody>    <tr>      <th>0</th>      <td>Cuboid(id=140307594351568)</td>      <td>0</td>      <td>sens1</td>      <td>0</td>      <td>8.003678e-01</td>      <td>1.413580e-13</td>      <td>-0.934878</td>    </tr>    <tr>      <th>1</th>      <td>Cuboid(id=140307594351568)</td>      <td>0</td>      <td>sens1</td>      <td>1</td>      <td>2.770095e-01</td>      <td>2.077218e-01</td>      <td>-0.530986</td>    </tr>    <tr>      <th>2</th>      <td>Cuboid(id=140307594351568)</td>      <td>0</td>      <td>sens2</td>      <td>0</td>      <td>9.167943e-01</td>      <td>0.000000e+00</td>      <td>0.050752</td>    </tr>    <tr>      <th>3</th>      <td>Cuboid(id=140307594351568)</td>      <td>0</td>      <td>sens2</td>      <td>1</td>      <td>4.250590e-01</td>      <td>3.187694e-01</td>      <td>-0.082663</td>    </tr>    <tr>      <th>4</th>      <td>Cuboid(id=140307594351568)</td>      <td>1</td>      <td>sens1</td>      <td>0</td>      <td>1.203621e+00</td>      <td>0.000000e+00</td>      <td>-1.213983</td>    </tr>    <tr>      <th>...</th>      <td>...</td>      <td>...</td>      <td>...</td>      <td>...</td>      <td>...</td>      <td>...</td>      <td>...</td>    </tr>    <tr>      <th>155</th>      <td>Cylinder1</td>      <td>18</td>      <td>sens2</td>      <td>1</td>      <td>-1.504683e-16</td>      <td>-1.973916e+00</td>      <td>-1.244052</td>    </tr>    <tr>      <th>156</th>      <td>Cylinder1</td>      <td>19</td>      <td>sens1</td>      <td>0</td>      <td>-2.084111e-16</td>      <td>1.622607e+00</td>      <td>-0.624080</td>    </tr>    <tr>      <th>157</th>      <td>Cylinder1</td>      <td>19</td>      <td>sens1</td>      <td>1</td>      <td>-3.549711e-15</td>      <td>1.254979e+01</td>      <td>-34.316622</td>    </tr>    <tr>      <th>158</th>      <td>Cylinder1</td>      <td>19</td>      <td>sens2</td>      <td>0</td>      <td>-8.962274e-17</td>      <td>4.626072e-01</td>      <td>-0.719364</td>    </tr>    <tr>      <th>159</th>      <td>Cylinder1</td>      <td>19</td>      <td>sens2</td>      <td>1</td>      <td>-1.593139e-16</td>      <td>-1.389858e+00</td>      <td>-1.805282</td>    </tr>  </tbody></table>

```python
import plotly.express as px

field = 'B'
px.line(
    B,
    x="path",
    y=f"{field}z",
    color="sensor",
    line_group="source",
    facet_col="source",
    symbol="pixel",
)
```
image

### CODE REVIEW

**Comment by OrtnerMichael** [comment]
@peter-leitner 

please add a minimal ParaView example with VTK data structure

**Comment by OrtnerMichael** [comment]
We should also include HDF5 output - I'll look into this

**Comment by peter-leitner** [comment]
> We should also include HDF5 output - I'll look into this

I/O from/to h5 is very easy with the h5py package. There is a lot of advantage when working with very large simulation data output. Also there are some powerful hdf5 visualizers out there (at least for linux) that allow quickly glancing through data slices without loading all of them into the buffer.

**Comment by peter-leitner** [comment]
> @peter-leitner
> 
> please add a minimal ParaView example with VTK data structure

```
import numpy as np
import magpylib as magpy

coil1 = magpy.Collection()
for z in np.linspace(-8, 8, 16):
    winding = magpy.current.Loop(
        current=100,
        diameter=10,
        position=(0,0,z),
    )
    coil1.add(winding)

coil1.show()

import pyvista as pv
grid = pv.UniformGrid()
grid.dimensions = (41, 41, 41)
grid.spacing = (2, 2, 2)
grid.origin = (-40, -40, -40)

# compute B-field and add as data to grid
grid['B'] = coil1.getB(grid.points)
grid['normB'] = np.sqrt(grid['B'][:,0]**2 + grid['B'][:,1]**2 + grid['B'][:,2]**2)
# save to vtk output for archiving/postprocessing the data
grid.save('grid.vtk')
```

coil

**Comment by Alexboiboi** [comment]
> We should also include HDF5 output - I'll look into this

I suggest to address this in another PR later and close it asap, since this PR is blocking further work (see #542)

**Review by OrtnerMichael — CHANGES_REQUESTED** [review]
- When only observer positions are handed in, a sensor is outo-generated, and will display in the data frame as sensor(id=123123123). This might be confusing to the user, but I see no better option.

- Using `pixel_agg` creates an error. This should be handled like `sumup`.

- Maybe we should have a similar label formatting option as in `describe` ? Otherwise I like the chosen style.

- The dataframe columns are also chosen well !

- I also like the chosen names `output` and options `ndarray`, `datframe`. Alternative options could be `numpy` and `pandas`.

**Pull request merged**
