### PR TITLE
Implement Mixed collections

### PR DESCRIPTION
**Pull request by Alexboiboi**
# Related Issues
#410 

# Notes
Implements Mixed Collections and the ability to mix Sensor and Source Collections

### CODE REVIEW

**Comment by OrtnerMichael** [comment]
-[ ] Collection is missing the display method

**Comment by OrtnerMichael** [comment]
- [ ] **Mixed Collection Bug**

`mixedCol.getB()` has wrong shape. 

```
import magpylib as magpy

s1=magpy.magnet.Sphere((1,2,3), 1)
s2=magpy.magnet.Cylinder((1,2,3), (1,1), (3,0,0))

x1=magpy.Sensor((1,0,3))
x2=magpy.Sensor((4,0,3))

c1 = magpy.Collection(s1,x1,s2,x2)

# this should be the same
B0 = magpy.getB([s1,s2], [x1,x2], sumup=True)
B1 = magpy.getB(c1.sources, c1.sensors, sumup=True)
B2 = magpy.getB(c1, c1)
B3 = c1.getB()

for B in [B0,B1,B2,B3]:
    print(B.shape)
```
produces
(2, 3)
(2, 3)
(2, 3)
(2, 2, 3)

**Comment by OrtnerMichael** [comment]
- [ ] **discussion**

das mit den unterschiedlichen __repr__ find cih komisch ... SourceCollection, SensorCollection oder MixedCollection. Wiso sollten wir das so explizit angeben ?

**Comment by Alexboiboi** [comment]
> - [ ] **discussion**
> 
> 
> 
> das mit den unterschiedlichen __repr__ find cih komisch ... SourceCollection, SensorCollection oder MixedCollection. Wiso sollten wir das so explizit angeben ?

Die Frage auch warum nicht?

**Comment by Alexboiboi** [comment]
> import magpylib as magpy
> 
> s1=magpy.magnet.Sphere((1,2,3), 1)
> s2=magpy.magnet.Cylinder((1,2,3), (1,1), (3,0,0))
> 
> x1=magpy.Sensor((1,0,3))
> x2=magpy.Sensor((4,0,3))
> 
> c1 = magpy.Collection(s1,x1,s2,x2)
> 
> # this should be the same
> B0 = magpy.getB([s1,s2], [x1,x2], sumup=True)
> B1 = magpy.getB(c1.sources, c1.sensors, sumup=True)
> B2 = magpy.getB(c1, c1)
> B3 = c1.getB()
> 
> for B in [B0,B1,B2,B3]:
>     print(B.shape)

I cannot reproduce the issue (commit a85091410e00faa74767d948203770401ffb4eef). For me all cases return `(2,3)`. Can you recheck this?

**Comment by OrtnerMichael** [comment]
- [ ] **Creates cryptic level2 uncaught error**

```
import magpylib as magpy
import numpy as np

s1=magpy.magnet.Sphere((1,2,3), 1)

x1=magpy.Sensor((1,0,3))

sCol = magpy.Collection(s1)
xCol = magpy.Collection(x1)

sCol.getB(sCol)
xCol.getB(xCol)
```

**Comment by OrtnerMichael** [comment]
- [ ] **bad input catching**

This should really generate the same error msg !!! - but its now caught at different levels. 

```
col.getB(col)
magpy.getB(col,col)
```

**Review by OrtnerMichael — APPROVED** [review]
ok

**Pull request merged**
