### PR TITLE
Allow for unset dimension or unset excitation when displaying objects.

### PR DESCRIPTION
**Pull request by Alexboiboi**
### Related Issues
- #638

### Notes
This PR allows to display objects that have no set dimension or vertices, or no set excitation.
Note that the `TriangularMesh` class cannot be initialized without setting vertices and faces, yet (see #641).

### Examples

```python
import magpylib as magpy

# test show if mag, curr or mom are not set

objs = [
    magpy.magnet.Cuboid(dimension=(1, 1, 1)),
    magpy.magnet.Cylinder(dimension=(1, 1)),
    magpy.magnet.CylinderSegment(dimension=(0, 1, 1, 45, 120)),
    magpy.magnet.Tetrahedron(vertices=[(0, 0, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1)]),
    magpy.magnet.TriangularMesh(
        vertices=((0, 0, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1)),
        faces=((0, 1, 2), (0, 1, 3), (0, 2, 3), (1, 2, 3)),
    ),
    magpy.magnet.Sphere(diameter=1),
    magpy.misc.Triangle(vertices=[(0, 0, 0), (1, 0, 0), (0, 1, 0)]),
    magpy.misc.Dipole(),
    magpy.current.Line(vertices=[[0, -1, 0], [0, 1, 0]]),
    magpy.current.Loop(diameter=1, current=0),
]
for i, o in enumerate(objs):
    o.move((i * 1.5, 0, 0))
magpy.show(*objs, style_magnetization_mode="color+arrow", layout_height=600)


# test completely unset objects
objs = [
    magpy.magnet.Cuboid(),
    magpy.magnet.Cylinder(),
    magpy.magnet.CylinderSegment(),
    magpy.magnet.Sphere(),
    magpy.magnet.Tetrahedron(),
    # magpy.magnet.TriangularMesh(), not possible yet
    magpy.misc.Triangle(),
    magpy.misc.Dipole(),
    magpy.current.Line(),
    magpy.current.Loop(),
]

for i, o in enumerate(objs):
    o.move((1.5 * i, 0, 0))
magpy.show(*objs, layout_height=600)
```
image

image

### CODE REVIEW

**Comment by OrtnerMichael** [comment]
When objects have been initialized without dimension plotly displays them nicely. Pyvista is hardly visible (also all dots seem to have the same color) and matpltlotlib not at all.

**Comment by Alexboiboi** [comment]
@OrtnerMichael 

Should work now, thanks for reviewing. It took a bit more work in the end. I also refactored some dimension and excitations checks since it is part of the topic

```python
import magpylib as magpy

for backend in magpy.SUPPORTED_PLOTTING_BACKENDS:
    c=magpy.magnet.Cuboid().move([(1.5 * i, j, 0) for j in range(10)], start=0)
    magpy.show(*objs, layout_height=600, zoom=1, backend=backend)
```

image
image
image

**Review by OrtnerMichael — APPROVED** [review]
looking good :)

**Comment by Alexboiboi** [comment]
fyi, pyvista does not support different symbols, hence the square instead of circle like in mpl or plotly

**Pull request merged**
