### PR TITLE
fix plot boundary error

### LINKED ISSUE #771: Very minor oddity/bug with show function when showing single straight line current
### Magpylib version

5.x (Latest)

### What happened?

I tried to run a simple test on just a wire using the following code, but the show function fails to zoom properly.

A = 90e-3
u=1e-3
w0 = magpy.current.Polyline(current=A,vertices=((0.0025,0.0025,-u/2),(0.0025,0.0025,u/2)),position=(0,0,0))
magpy.show(w0)

The show function is zoomed out in a 1m x 1m x 1m box which shows nothing. 

If you alter the line a bit to have a tilt to one side however, eg changes position from 0.25 to 0.24 one place, the show function works again.

w0 = magpy.current.Polyline(current=A,vertices=((0.0025,0.0025,-u/2),(0.0025,0.0024,u/2)),position=(0,0,0))

Alternatively once you have two currents two different places it also works again, so it most likely is only in the single current case, so really a minor and niche bug.

Just a heads up in case it is not a known issue. Otherwise appologies for spam!

### Code example

```Python
import magpylib as magpy
A = 90e-3
u=1e-3
w0 = magpy.current.Polyline(current=A,vertices=((0.0025,0.0025,-u/2),(0.0025,0.0025,u/2)),position=(0,0,0))
magpy.show(w0)
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by OrtnerMichael**
- Fixes #771

### CODE REVIEW

**Comment by OrtnerMichael** [comment]
hi @Alexboiboi 

Do you know why the macos tests are all failing?

br

**Comment by OrtnerMichael** [comment]
ah ... i think its the doctests ... again :(

**Comment by OrtnerMichael** [comment]
its the same problem we had with numerical stability where windows and macs yielded different results at sigularities because they treat floating point somehow differently - in this case resulting in different zeros

**Comment by OrtnerMichael** [comment]
@Alexboiboi 

now its ready for review :)

**Review by Alexboiboi — APPROVED** [review]
We got there 😄

**Pull request merged**
