### PR TITLE
Update pre-commit hooks for python 3.8+

### PR DESCRIPTION
**Pull request by Alexboiboi**
update hooks:
- reorder-python-imports
- pyupgrade

@OrtnerMichael, don't squash, just merge please

### CODE REVIEW

**Comment by OrtnerMichael** [comment]
test got stuck - rerunning test

**Comment by Alexboiboi** [comment]
> test got stuck - rerunning test

did you retrigger anything?  On the azure-pipepline site it shows that all tests are through but it does not forward the message to github apparently. 
I created an empty commit to retrigger the CI. We will see then if it works. 

Maybe it is the time to switch to github workflows for the CI. Also I don't really get why codeQL is taking ages to finish

**Comment by Alexboiboi** [comment]
@OrtnerMichael now ready

**Review by OrtnerMichael — APPROVED** [review]
by the power invested in me I graciously accept this pr. may thy code run well

**Pull request merged**
