### PR TITLE
Improve extra user 3d model

### PR DESCRIPTION
**Pull request by Alexboiboi**
# Related Issues
#414

# Notes

### CODE REVIEW

**Comment by OrtnerMichael** [comment]
There is a color problem in Plotly:

with matplotlib backend the `extra` tracecolor is automatically the object color.

image

in Plotly this is not the case
image

generated by the following code
```
import numpy as np
import magpylib as magpy

MOD1 = {
    'backend': 'matplotlib',
    'trace': {
        'type':'plot',
        'xs': np.array([-1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, 1,  1, -1])/2, 
        'ys': np.array([-1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1])/2, 
        'zs': np.array([-1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1])/2,
        'ls': '-',},
    'show': True}
MOD2 = {
        'backend': 'plotly',
        'trace': {
            'type': 'scatter3d',
            'x': np.array([-1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, 1,  1, -1])/2, 
            'y': np.array([-1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1])/2, 
            'z': np.array([-1, -1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1])/2,
            'mode':'lines',
        },
        'show': True,
    }

s1 = magpy.magnet.Sphere((1,2,3),1)
s1.style.model3d.extra=[MOD1, MOD2]
s1.style.color='r'

s2 = magpy.magnet.Sphere((1,2,3),1,(5,0,0))
s2.style.model3d.extra=[MOD1, MOD2]
s2.style.color='g'

s3 = magpy.magnet.Sphere((1,2,3),1,(0,5,0))
s3.style.model3d.extra=[MOD1, MOD2]
s3.style.color='b'

s1.rotate_from_angax(45,'z')

magpy.display(s1,s2,s3, style_magnetization_show=False)
magpy.display(s1,s2,s3, backend='plotly', style_magnetization_show=False)

```

**Comment by OrtnerMichael** [comment]
it would be cool if the input of `src.style.model3d.extra` would accept single dicts like

`src.style.model3d.extra=dict1`

right now it only accepts

`src.style.model3d.extra=[dict1]`

**Comment by Alexboiboi** [comment]
I implemented the "minifeature". The user can provide a dictionary but it will we encapsulated into a list. Later access has to be with `__getitem__`:

example:

```python
model3d.extra = dict() # setting property
print(modeld3d.extra[0])` # access property
```
Should we rename `extra` to `extras` to be more explicit ?

**Comment by Alexboiboi** [comment]
> in Plotly this is not the case

fixed in d6a9ab2e04e9e660b3475f461fb6cf26c768ffce

**Review by OrtnerMichael — APPROVED** [review]
Looks good now !!!

`extra` is a very acceptable name - alternatives (`user`, `user_defined`, `external` ) are no good

changing this will not lead to a breaking change !!!

**Pull request merged**
